# Generated by Django 5.0.3 on 2024-03-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(default='No city', max_length=100)),
                ('capacity', models.IntegerField(default=1)),
                ('description', models.TextField(default='No description')),
                ('parking', models.TextField(default='No parking')),
                ('policies', models.TextField(default='No policies')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.URLField(default='fake.com')),
                ('description', models.TextField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tick_it.venue')),
            ],
        ),
    ]
