# Generated by Django 5.0.3 on 2024-03-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(default='www.fake.com'),
        ),
    ]
