# Generated by Django 5.0.3 on 2024-03-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tick_it', '0002_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='parking',
        ),
    ]
