# Generated by Django 5.0.3 on 2024-03-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_it', '0003_remove_venue_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='parking',
            field=models.TextField(default='No parking'),
        ),
    ]
